# Site settings
title: Musings By Matthew
email: musingsbymatthew@mklauber.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: "@m_lauber"
github_username:  mklauber

# Build settings
markdown: kramdown
highlighter: rouge
exerpt_separator: <!--more-->

category_names:
  "ai": "AI"
  "blog": "This Blog"
  "game-dev": "Game Development"
  "hoplite": "Hoplite Clone"
